MinPro334_GroupA/MinPro334_GroupA/Models/ErrorViewModel.cs
namespace MinPro334_GroupA.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MinPro334_GroupA/MinPro334_GroupA/Controllers/AuthController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MinPro334_GroupA.datamodels;
using MinPro334_GroupA.Services;
using MinPro334_GroupA.viewmodels;

namespace MinPro334_GroupA.Controllers
{
    public class AuthController : Controller
    {
        private AuthService authService;

        VMResponse respon = new VMResponse();
        public AuthController(AuthService _authService)
        {
            authService = _authService;

        }
        public IActionResult Login()
        {
            return PartialView();
        }

        [HttpPost]
        public async Task<JsonResult> LoginSubmit(string email, string password)
        {
            VMMUser user = await authService.CheckLogin(email, password);         
            if (user != null)
            {
                respon.Message = $"Hello, Welcome to Modernize";
                HttpContext.Session.SetString("FullName", user.Fullname);
                HttpContext.Session.SetInt32("IdUser", (int)user.Id);
                HttpContext.Session.SetInt32("IdRole", (int)user.RoleId);
                HttpContext.Session.SetString("ImagePath", user.ImagePath);
            }
            else
            {
                respon.Success = false;
                respon.Message = $"Oops, {email} not found or password is wrong, please check again";
            }
            return Json(new { dataRespon = respon });
        }
        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }

    }
}

MinPro334_GroupA/MinPro334_GroupA/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MinPro334_GroupA.Models;
using System.Diagnostics;

namespace MinPro334_GroupA.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MinPro334_GroupA/MinPro334_GroupA/Views/Home/Index.cshtml
@using MinPro334_GroupA.Services;

@inject AuthService authService
@{
    ViewData["Title"] = "Home Page";
    int IdRole = @Context.Session.GetInt32("IdRole") ?? 0; // Menggunakan ?? 0 untuk mengatasi null jika sesi tidak ada
    var menu = await authService.MenuAccess(IdRole);
}

@*     <div class="text-center">
        <h1 class="display-4">Welcome</h1>
        <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    </div> *@
  
    <div class="row">
        @foreach (var parent in menu)
        {
            @foreach (var child in parent.ListChild)
            {
                <div class="col-md-3">
                    <div class="card" style="width: 15rem;">
                        <img src="~/@child.BigIcon" class="card-img-top rounded-0" alt="..." style="height: 200px;">
                        <div class="card-body">
                            <h5 class="text-center">@child.Name</h5>
                        </div>
                    </div>
                </div>
            }

        }
        </div>
    
    

MinPro334_GroupA/MinPro334_GroupA/Views/Shared/_Header.cshtml
@using MinPro334_GroupA.Services;

@inject AuthService authService
@{
    int IdRole = @Context.Session.GetInt32("IdRole") ?? 0; // Menggunakan ?? 0 untuk mengatasi null jika sesi tidak ada
    string FullName = @Context.Session.GetString("FullName") ?? "";
    string ImagePath = @Context.Session.GetString("ImagePath") ?? "";

}
<!--  Header Start -->
<header class="app-header">
    <input type="hidden" class="idrole" value="@IdRole"/>
    <nav class="navbar navbar-expand-lg navbar-light">
        <ul class="navbar-nav">
            <li class="nav-item d-block d-xl-none">
                <a class="nav-link sidebartoggler nav-icon-hover" id="headerCollapse" href="javascript:void(0)">
                    <i class="ti ti-menu-2"></i>
                </a>
            </li>
            <li class="nav-item nav-link">
                <div class="brand-logo d-flex align-items-center justify-content-between">
                    <a asp-action="Index" class="text-nowrap logo-img">
                        @if (IdRole == 0)
                        {
                            <img src="~/Modernize-1.0.0/src/assets/images/logos/med.png" width="200" alt="" />
                        }
                    </a>
                    <div class="close-btn d-xl-none d-block sidebartoggler cursor-pointer" id="sidebarCollapse">
                        <i class="ti ti-x fs-8"></i>
                    </div>
                </div>
            </li>
        </ul>
        <div class="navbar-collapse justify-content-end px-0" id="navbarNav">
            <ul class="navbar-nav flex-row ms-auto align-items-center justify-content-end">
                <li class="nav-item dropdown">
                    @{
                        if (IdRole != 0)
                        {
                            <a class="nav-link dropdown-toggle" href="javascript:void(0)" id="drop2" data-bs-toggle="dropdown"
                               aria-expanded="false">
                                    <span>Hello,</span> <span class="text-dark">@FullName</span>
                                <img src="~/@ImagePath" alt="" width="35" height="35" class="rounded-circle">
                            </a>
                        }
                        else
                        {
                           
                            <button id="btn_daftar" class="btn btn-primary ml-3">Daftar</button>

                            <button id="btn_login" class="btn btn-primary">Login</button>
                        }
                    }
                   @*  <a class="nav-link nav-icon-hover" href="javascript:void(0)" id="drop2" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        <img src="~/Modernize-1.0.0/src/assets/images/profile/user-1.jpg" alt="" width="35" height="35" class="rounded-circle">
                    </a> *@
                    <div class="dropdown-menu dropdown-menu-end dropdown-menu-animate-up" aria-labelledby="drop2">
                        <div class="message-body">
                            <a href="javascript:void(0)" class="d-flex align-items-center gap-2 dropdown-item">
                                <i class="ti ti-user fs-6"></i>
                                <p class="mb-0 fs-3">My Profile</p>
                            </a>
                            <a href="javascript:void(0)" class="d-flex align-items-center gap-2 dropdown-item">
                                <i class="ti ti-mail fs-6"></i>
                                <p class="mb-0 fs-3">My Account</p>
                            </a>
                            <a href="javascript:void(0)" class="d-flex align-items-center gap-2 dropdown-item">
                                <i class="ti ti-list-check fs-6"></i>
                                <p class="mb-0 fs-3">My Task</p>
                            </a>
                            <a asp-controller="Auth" asp-action="Logout" class="btn btn-outline-primary mx-3 mt-2 d-block">Logout</a>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
</header>
<!--  Header End -->

<script>
    $("#btn_login").click(function () {
        $("#modal_body").empty()
        $("#modal_body").load("Auth/Login")
        $("#modal_judul").empty()
        $("#modal_judul").text("Login")
        $(".modal-dialog").removeClass("modal-xl")
        $("#my_modal").modal("show")


    })

    $("#btn_daftar").click(function(){
        $("#modal_body").empty()
        $("#modal_body").load("Daftar/Register")

        $("#modal_judul").empty()
        $("#modal_judul").text("Daftar")

        $("#my_modal").modal("show")
        $(".modal-dialog").addClass("modal-xl")
        $(".modal-dialog").removeClass("modal-xl")

    })

   
    var idrole = $(".idrole").val()
    if (idrole == 0) {
        $(".app-header").attr("style", "margin-left:-130px")
    }

</script>

MinPro334_GroupA/MinPro334_GroupA/Views/Shared/_Layout.cshtml
@{
    var modal_title = "";
    int IdRole = @Context.Session.GetInt32("IdRole") ?? 0;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MinPro334_GroupA</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MinPro334_GroupA.styles.css" asp-append-version="true" />
    <script src="~/Modernize-1.0.0/src/assets/libs/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/Modernize-1.0.0/src/assets/libs/apexcharts/dist/apexcharts.min.js"></script>
   @*  <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"> *@
    <title>Modernize Free</title>
    <link rel="shortcut icon" type="image/png" href="~/Modernize-1.0.0/src/assets/images/logos/favicon.png"/>
    <link rel="stylesheet" href="~/Modernize-1.0.0/src/assets/css/styles.min.css" />
    <!--Sweetalert2-->
    <script src="~/Modernize-1.0.0/plugins/sweetalert2/sweetalert2.js"></script>

@*     <script src="~/Modernize-1.0.0/src/assets/libs/jquery/dist/jquery.min.js"></script>
 *@
</head>
<body>

    <input type="hidden" class="idrole" value="@IdRole"/>

    <div class="page-wrapper" id="main-wrapper" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
         data-sidebar-position="fixed" data-header-position="fixed">
        <partial name="_Sidebar" />
        <!--  Main wrapper -->
        <div class="body-wrapper">
            <partial name="_Header" />
            <div class="container-fluid container-content">
                <div class="container">
                    <main role="main" class="pb-3">
                        @RenderBody()
                    </main>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="my_modal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="modal_judul" aria-hidden="true">
        <div class="modal-dialog modal-xl">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="modal_judul">@modal_title</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body" id="modal_body">
                </div>
            </div>
        </div>
    </div>

 
    <footer class="border-top footer text-muted">
        <div class="container d-flex justify-content-end">
            &copy; 2023 - MiniProjectGroupA - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
   @*  <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script> 
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)*@


    <script src="~/Modernize-1.0.0/src/assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/Modernize-1.0.0/src/assets/js/sidebarmenu.js"></script>
    <script src="~/Modernize-1.0.0/src/assets/js/app.min.js"></script>
    <script src="~/Modernize-1.0.0/src/assets/libs/apexcharts/dist/apexcharts.min.js"></script>
    <script src="~/Modernize-1.0.0/src/assets/libs/simplebar/dist/simplebar.js"></script>
    <script src="~/Modernize-1.0.0/src/assets/js/dashboard.js"></script>

   
    <script>
        var idrole = $(".idrole").val()
        if (idrole == 0)
        { 
             $(".container-content").attr("style", "margin-left:-110px") 
        }
    </script>
</body>
</html>

MinPro334_GroupA/MinPro334_GroupA/Views/Shared/_Sidebar.cshtml
@using MinPro334_GroupA.Services;

@inject AuthService authService

@{
    int IdRole = @Context.Session.GetInt32("IdRole") ?? 0; // Menggunakan ?? 0 untuk mengatasi null jika sesi tidak ada
    var menu = await authService.MenuAccess(IdRole);
}

@if (IdRole != 0)
{
<aside class="left-sidebar">
    <div>
        <div class="brand-logo d-flex align-items-center justify-content-between">
            <a asp-action="Index" class="text-nowrap logo-img">
                <img src="~/Modernize-1.0.0/src/assets/images/logos/med.png" width="200" alt="" />
            </a>
            <div class="close-btn d-xl-none d-block sidebartoggler cursor-pointer" id="sidebarCollapse">
                <i class="ti ti-x fs-8"></i>
            </div>
        </div>
        <nav class="sidebar-nav scroll-sidebar" data-simplebar="">
            <ul id="sidebarnav">
                    @foreach (var parent in menu)
                    {
                        <li class="nav-small-cap">
                            <i class="@parent.SmallIcon"></i>
                            <span class="hide-menu">@parent.Name</span>
                        </li>
                        @foreach (var child in parent.ListChild)
                        {
                            <li class="sidebar-item">
                                <a class="sidebar-link" href="./index.html" aria-expanded="false">
                                    <span>
                                        <i class="@child.SmallIcon"></i>
                                    </span>
                                    <span class="hide-menu">@child.Name</span>
                                </a>
                            </li>
                        }
                    }
            </ul>
        </nav>
    </div>
</aside>
}
@* 

 